[meta]
name = "Checkpoint Counter"
author = "Phlarx"
category = "Race"

siteid = 79
version = "3.1.0"

blocks = [ "Plugin_CheckpointCounter" ]

[script]
module = "CP"
exports = [ "CheckpointAPI.as" ]
optional_dependencies = [ "PlayerState" ]
